// File generated by FlutterFire CLI for learnquest-87aeb
// ─── firebase_options.dart ────────────────────────────────────────────────────
// DO NOT edit this file — regenerate via FlutterFire CLI if config changes.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured yet — add GoogleService-Info.plist');
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS not configured yet');
      case TargetPlatform.windows:
        return web; // uses web config for Windows desktop
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // ── Android ───────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADxDInEX3F0Jmqg6q3HoULkXmxo2k95XU',
    appId: '1:566613334158:android:bfb61a8ded514d1a2c51df',
    messagingSenderId: '566613334158',
    projectId: 'learnquest-87aeb',
    storageBucket: 'learnquest-87aeb.firebasestorage.app',
  );

  // ── Web (also used for Windows desktop) ───────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADxDInEX3F0Jmqg6q3HoULkXmxo2k95XU',
    appId: '1:566613334158:android:bfb61a8ded514d1a2c51df',
    messagingSenderId: '566613334158',
    projectId: 'learnquest-87aeb',
    storageBucket: 'learnquest-87aeb.firebasestorage.app',
  );
}
